#! /opt/homebrew/bin/fish

micromamba activate default

cd $HOME/Dropbox/shared/Liz/tiller
python scripts/download_data.py
python scripts/download_ticker_data.py
papermill tiller-analysis.ipynb tiller-analysis-autorun.ipynb
jupyter nbconvert --to=html --no-input tiller-analysis-autorun.ipynb

python weekly-spending.py --email
